version: 2.1
commands:
jobs:
  build:
    environment:
      - GOPATH: /home/circleci/go
      - GOTEST_PALETTE: yellow,blue
      - CI: hoge
    docker:
      - image: circleci/golang:1.12
    working_directory: /home/circleci/go/src/github.com/k-kurikuri/advent-calendar
    steps:
      - checkout
      - run: go get -u github.com/rakyll/gotest
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - run: gotest -v -race
workflows:
  version: 2
  build:
    jobs:
      - build